# Generated by Django 5.1.4 on 2024-12-26 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='role',
            field=models.CharField(choices=[('Student', 'student'), ('Tutor', 'tutor'), ('Admin', 'admin')], default='admin', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='role',
            field=models.CharField(choices=[('Student', 'student'), ('Tutor', 'tutor'), ('Admin', 'admin')], default='student', max_length=10),
        ),
        migrations.AddField(
            model_name='tutor',
            name='role',
            field=models.CharField(choices=[('Student', 'student'), ('Tutor', 'tutor'), ('Admin', 'admin')], default='tutor', max_length=10),
        ),
    ]
