# Generated by Django 5.1.4 on 2024-12-27 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_admin_role_student_role_tutor_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(max_length=12),
        ),
    ]
